// swift-tools-version: 5.9
// =============================================================================
// Package.swift — LiteRTLM-Swift-fork
// =============================================================================
// IMPORTANT: The MANIFEST-MANAGED block below is REGENERATED by
//   scripts/rewrap-xcframework.sh (run with --tag <tag>).
// Do NOT hand-edit any lines between MANIFEST-MANAGED:BEGIN and
// MANIFEST-MANAGED:END — those edits will be silently overwritten on the
// next release run.
//
// To update checksums/URLs:
//   ./scripts/rewrap-xcframework.sh --tag v<upstream>+rewrap.<n>
// which regenerates BOTH binaryTarget entries as a pair from
// rewrap-manifest.json's xcframeworks[] array.
//
// To verify no drift:
//   make verify   (or ./scripts/verify-consumption.sh)
// =============================================================================

import PackageDescription

let package = Package(
    name: "LiteRTLM-Swift-fork",
    platforms: [
        .iOS(.v17),
        .macOS(.v14),
    ],
    products: [
        .library(name: "LiteRTLMSwift", targets: ["LiteRTLMSwift"]),
    ],
    targets: [
        .target(
            name: "LiteRTLMSwift",
            dependencies: ["CLiteRTLM", "GemmaModelConstraintProvider"],
            path: "Sources/LiteRTLMSwift"
        ),
        // MANIFEST-MANAGED:BEGIN — regenerated by scripts/rewrap-xcframework.sh; do NOT hand-edit between these markers.
        .binaryTarget(
            name: "CLiteRTLM",
            url: "https://github.com/helenkwok/LiteRTLM-Swift/releases/download/v0.10.2+rewrap.5/CLiteRTLM-v0.10.2+rewrap.5.xcframework.zip",
            checksum: "ba2d0c9a6b2a44fd447890b58b9220cdddf14356cf64c3dbd6ce77c94d3dfc1a"
        ),
        .binaryTarget(
            name: "GemmaModelConstraintProvider",
            url: "https://github.com/helenkwok/LiteRTLM-Swift/releases/download/v0.10.2+rewrap.5/GemmaModelConstraintProvider-v0.10.2+rewrap.5.xcframework.zip",
            checksum: "58f2db564c22efc55dd6a6596dae83e4b044036699347befdebda39648e4a6f4"
        ),
        // MANIFEST-MANAGED:END
    ]
)
