// swift-tools-version: 5.9
// =============================================================================
// Package.swift — LiteRTLM-Swift-fork
// =============================================================================
// IMPORTANT: The MANIFEST-MANAGED block below is REGENERATED by
//   scripts/rewrap-xcframework.sh (run with --tag <tag>).
// Do NOT hand-edit any lines between MANIFEST-MANAGED:BEGIN and
// MANIFEST-MANAGED:END — those edits will be silently overwritten on the
// next release run.
//
// To update checksums/URLs:
//   ./scripts/rewrap-xcframework.sh --tag v<upstream>+rewrap.<n>
// which regenerates BOTH binaryTarget entries as a pair from
// rewrap-manifest.json's xcframeworks[] array.
//
// To verify no drift:
//   make verify   (or ./scripts/verify-consumption.sh)
// =============================================================================

import PackageDescription

let package = Package(
    name: "LiteRTLM-Swift-fork",
    platforms: [
        .iOS(.v17),
        .macOS(.v14),
    ],
    products: [
        .library(name: "LiteRTLMSwift", targets: ["LiteRTLMSwift"]),
    ],
    targets: [
        .target(
            name: "LiteRTLMSwift",
            dependencies: ["LiteRTLMBinary", "GemmaModelConstraintProviderBinary"],
            path: "Sources/LiteRTLMSwift"
        ),
        // MANIFEST-MANAGED:BEGIN — regenerated by scripts/rewrap-xcframework.sh; do NOT hand-edit between these markers.
        .binaryTarget(
            name: "LiteRTLMBinary",
            url: "https://github.com/helenkwok/LiteRTLM-Swift/releases/download/v0.10.2+rewrap.1/LiteRTLM-rewrapped-v0.10.2+rewrap.1.xcframework.zip",
            checksum: "10565a593a70cd5f4e4cae7b56be59998ab358655831c2ff1b687578640cdf60"
        ),
        .binaryTarget(
            name: "GemmaModelConstraintProviderBinary",
            url: "https://github.com/helenkwok/LiteRTLM-Swift/releases/download/v0.10.2+rewrap.1/GemmaModelConstraintProvider-v0.10.2+rewrap.1.xcframework.zip",
            checksum: "4d4cd8c8cfa8ca0603d818f2c1478155d7d62193f07d0045f3182cee61a879d8"
        ),
        // MANIFEST-MANAGED:END
    ]
)
