// swift-tools-version: 5.9
// =============================================================================
// Package.swift — LiteRTLM-Swift-fork
// =============================================================================
// IMPORTANT: The MANIFEST-MANAGED block below is REGENERATED by
//   scripts/rewrap-xcframework.sh (run with --tag <tag>).
// Do NOT hand-edit any lines between MANIFEST-MANAGED:BEGIN and
// MANIFEST-MANAGED:END — those edits will be silently overwritten on the
// next release run.
//
// To update checksums/URLs:
//   ./scripts/rewrap-xcframework.sh --tag v<upstream>+rewrap.<n>
// which regenerates BOTH binaryTarget entries as a pair from
// rewrap-manifest.json's xcframeworks[] array.
//
// To verify no drift:
//   make verify   (or ./scripts/verify-consumption.sh)
// =============================================================================

import PackageDescription

let package = Package(
    name: "LiteRTLM-Swift-fork",
    platforms: [
        .iOS(.v17),
        .macOS(.v14),
    ],
    products: [
        .library(name: "LiteRTLMSwift", targets: ["LiteRTLMSwift"]),
    ],
    targets: [
        .target(
            name: "LiteRTLMSwift",
            dependencies: ["LiteRTLMBinary", "GemmaModelConstraintProviderBinary"],
            path: "Sources/LiteRTLMSwift"
        ),
        // MANIFEST-MANAGED:BEGIN — regenerated by scripts/rewrap-xcframework.sh; do NOT hand-edit between these markers.
        .binaryTarget(
            name: "LiteRTLMBinary",
            url: "https://github.com/helenkwok/LiteRTLM-Swift/releases/download/v0.10.2+rewrap.2/CLiteRTLM-v0.10.2+rewrap.2.xcframework.zip",
            checksum: "b9d1019abc622610b139cc6b9ecbad8a2602571f00e910643f8075650552211a"
        ),
        .binaryTarget(
            name: "GemmaModelConstraintProviderBinary",
            url: "https://github.com/helenkwok/LiteRTLM-Swift/releases/download/v0.10.2+rewrap.2/GemmaModelConstraintProvider-v0.10.2+rewrap.2.xcframework.zip",
            checksum: "3abcff47b287241b06c805258c38b1e4f9c922a50fa381c52a5579e68f11e9a4"
        ),
        // MANIFEST-MANAGED:END
    ]
)
