// AUTO-GENERATED by scripts/rewrap-xcframework.sh — do not edit by hand.
// Re-run the script with --tag <tag> to regenerate.
// Schema: Phase 14-08, D-31 (generated-source approach for SPM ergonomics).

import Foundation

public enum RewrapManifest {
    public struct Entry {
        public let xcframeworkName: String
        public let swiftTargetName: String
        public let zipSHA256: String
        public let releaseAssetURL: String
        public init(xcframeworkName: String, swiftTargetName: String,
                    zipSHA256: String, releaseAssetURL: String) {
            self.xcframeworkName = xcframeworkName
            self.swiftTargetName = swiftTargetName
            self.zipSHA256 = zipSHA256
            self.releaseAssetURL = releaseAssetURL
        }
    }
    public static let schemaVersion = 1
    public static let upstreamVersion = "v0.10.2"
    public static let tag = "v0.10.2+rewrap.3"
    public static let forkSHA = "1df672510c75382051c522f274750ea55248b1cf"
    public static let entries: [Entry] = [
        Entry(xcframeworkName: "CLiteRTLM.xcframework",
              swiftTargetName: "LiteRTLMBinary",
              zipSHA256: "ba2d0c9a6b2a44fd447890b58b9220cdddf14356cf64c3dbd6ce77c94d3dfc1a",
              releaseAssetURL: "https://github.com/helenkwok/LiteRTLM-Swift/releases/download/v0.10.2+rewrap.3/CLiteRTLM-v0.10.2+rewrap.3.xcframework.zip"),
        Entry(xcframeworkName: "GemmaModelConstraintProvider.xcframework",
              swiftTargetName: "GemmaModelConstraintProviderBinary",
              zipSHA256: "58f2db564c22efc55dd6a6596dae83e4b044036699347befdebda39648e4a6f4",
              releaseAssetURL: "https://github.com/helenkwok/LiteRTLM-Swift/releases/download/v0.10.2+rewrap.3/GemmaModelConstraintProvider-v0.10.2+rewrap.3.xcframework.zip"),
    ]
}
