// AUTO-GENERATED by scripts/rewrap-xcframework.sh — do not edit by hand.
// Re-run the script with --tag <tag> to regenerate.
// Schema: Phase 14-08, D-31 (generated-source approach for SPM ergonomics).
//
// This file is a placeholder; a real release run will populate the checksums
// and URLs. Until then, RewrapManifest.entries[*].zipSHA256 contains the
// placeholder string below (which Layer C will detect and reject).

import Foundation

public enum RewrapManifest {
    public struct Entry {
        public let xcframeworkName: String
        public let swiftTargetName: String
        public let zipSHA256: String
        public let releaseAssetURL: String
        public init(xcframeworkName: String, swiftTargetName: String,
                    zipSHA256: String, releaseAssetURL: String) {
            self.xcframeworkName = xcframeworkName
            self.swiftTargetName = swiftTargetName
            self.zipSHA256 = zipSHA256
            self.releaseAssetURL = releaseAssetURL
        }
    }
    public static let schemaVersion = 1
    public static let upstreamVersion = "v0.7.3"
    public static let tag = "v0.7.3+rewrap.1"
    public static let forkSHA = "pending"
    public static let entries: [Entry] = [
        Entry(xcframeworkName: "LiteRTLM-rewrapped.xcframework",
              swiftTargetName: "LiteRTLMBinary",
              zipSHA256: "0000000000000000000000000000000000000000000000000000000000000000",
              releaseAssetURL: "https://github.com/helenkwok/LiteRTLM-Swift/releases/download/v0.7.3+rewrap.1/LiteRTLM-rewrapped-v0.7.3+rewrap.1.xcframework.zip"),
        Entry(xcframeworkName: "GemmaModelConstraintProvider.xcframework",
              swiftTargetName: "GemmaModelConstraintProviderBinary",
              zipSHA256: "0000000000000000000000000000000000000000000000000000000000000000",
              releaseAssetURL: "https://github.com/helenkwok/LiteRTLM-Swift/releases/download/v0.7.3+rewrap.1/GemmaModelConstraintProvider-v0.7.3+rewrap.1.xcframework.zip"),
    ]
}
