// AUTO-GENERATED by scripts/rewrap-xcframework.sh — do not edit by hand.
// Re-run the script with --tag <tag> to regenerate.
// Schema: Phase 14-08, D-31 (generated-source approach for SPM ergonomics).

import Foundation

public enum RewrapManifest {
    public struct Entry {
        public let xcframeworkName: String
        public let swiftTargetName: String
        public let zipSHA256: String
        public let releaseAssetURL: String
        public init(xcframeworkName: String, swiftTargetName: String,
                    zipSHA256: String, releaseAssetURL: String) {
            self.xcframeworkName = xcframeworkName
            self.swiftTargetName = swiftTargetName
            self.zipSHA256 = zipSHA256
            self.releaseAssetURL = releaseAssetURL
        }
    }
    public static let schemaVersion = 1
    public static let upstreamVersion = "v0.10.2"
    public static let tag = "v0.10.2+rewrap.2"
    public static let forkSHA = "4c107b8fe4d9da661e6e325495175710c9026e99"
    public static let entries: [Entry] = [
        Entry(xcframeworkName: "CLiteRTLM.xcframework",
              swiftTargetName: "LiteRTLMBinary",
              zipSHA256: "b9d1019abc622610b139cc6b9ecbad8a2602571f00e910643f8075650552211a",
              releaseAssetURL: "https://github.com/helenkwok/LiteRTLM-Swift/releases/download/v0.10.2+rewrap.2/CLiteRTLM-v0.10.2+rewrap.2.xcframework.zip"),
        Entry(xcframeworkName: "GemmaModelConstraintProvider.xcframework",
              swiftTargetName: "GemmaModelConstraintProviderBinary",
              zipSHA256: "3abcff47b287241b06c805258c38b1e4f9c922a50fa381c52a5579e68f11e9a4",
              releaseAssetURL: "https://github.com/helenkwok/LiteRTLM-Swift/releases/download/v0.10.2+rewrap.2/GemmaModelConstraintProvider-v0.10.2+rewrap.2.xcframework.zip"),
    ]
}
